# Netlify Build Settings
[build]
  # Folder where your built React app will be published
  publish = "build"
  # Command Netlify runs to build your app
  command = "npm run build"

# Plugins (if any Netlify-specific plugins are used)
# Note: framer-motion is NOT a Netlify plugin, so do NOT list it here.
[[plugins]]
package = "react-netlify-forms"
